spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/portfolio
    username: ${DB_USERNAME:portfolio_app}
    password: ${DB_PASSWORD:portfolio1234}

file:
  upload-dir: ${FILE_UPLOAD_DIR:${user.home}/portfolio-uploads}
